# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ebs_msg.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rebs_msg.proto\x12\x07\x65\x62s_msg\"\x80\x01\n\x07\x43onnect\x12&\n\x04type\x18\x01 \x01(\x0e\x32\x18.ebs_msg.Connect.SrcType\x12\n\n\x02id\x18\x02 \x01(\r\"A\n\x07SrcType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0e\n\nSUBSCRIBER\x10\x01\x12\r\n\tPUBLISHER\x10\x02\x12\n\n\x06\x42ROKER\x10\x03\"\xb8\x01\n\tCondition\x12\x12\n\x05\x66ield\x18\x01 \x01(\tH\x00\x88\x01\x01\x12,\n\x02Op\x18\x02 \x01(\x0e\x32\x1b.ebs_msg.Condition.OperatorH\x01\x88\x01\x01\x12\x12\n\x05value\x18\x03 \x01(\tH\x02\x88\x01\x01\":\n\x08Operator\x12\x06\n\x02\x45Q\x10\x00\x12\x06\n\x02NE\x10\x01\x12\x06\n\x02GT\x10\x02\x12\x06\n\x02GE\x10\x03\x12\x06\n\x02LT\x10\x04\x12\x06\n\x02LE\x10\x05\x42\x08\n\x06_fieldB\x05\n\x03_OpB\x08\n\x06_value\"L\n\x0cSubscription\x12%\n\tcondition\x18\x01 \x03(\x0b\x32\x12.ebs_msg.Condition\x12\x15\n\rsubscriber_id\x18\x02 \x01(\r\"\xbe\x01\n\x0bPublication\x12\x14\n\x07\x63ompany\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05value\x18\x02 \x01(\x01H\x01\x88\x01\x01\x12\x11\n\x04\x64rop\x18\x03 \x01(\x01H\x02\x88\x01\x01\x12\x16\n\tvariation\x18\x04 \x01(\x01H\x03\x88\x01\x01\x12\x11\n\x04\x64\x61te\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\x11\n\tsource_id\x18\x06 \x01(\rB\n\n\x08_companyB\x08\n\x06_valueB\x07\n\x05_dropB\x0c\n\n_variationB\x07\n\x05_date\"?\n\x0bUnsubscribe\x12\x1c\n\x0fsubscription_id\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x12\n\x10_subscription_idb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ebs_msg_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONNECT._serialized_start=27
  _CONNECT._serialized_end=155
  _CONNECT_SRCTYPE._serialized_start=90
  _CONNECT_SRCTYPE._serialized_end=155
  _CONDITION._serialized_start=158
  _CONDITION._serialized_end=342
  _CONDITION_OPERATOR._serialized_start=257
  _CONDITION_OPERATOR._serialized_end=315
  _SUBSCRIPTION._serialized_start=344
  _SUBSCRIPTION._serialized_end=420
  _PUBLICATION._serialized_start=423
  _PUBLICATION._serialized_end=613
  _UNSUBSCRIBE._serialized_start=615
  _UNSUBSCRIBE._serialized_end=678
# @@protoc_insertion_point(module_scope)
